In [70]:
import pandas as pd
import numpy as np

from pymongo import MongoClient
from dotenv import load_dotenv
import os

In [71]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [72]:
load_dotenv()

client = MongoClient(os.getenv("MONGODB_URI"))

db = client["aqi_predictor"]

collection = db["aqi_features"]

df = pd.DataFrame(list(collection.find()))

In [73]:
if "_id" in df.columns:
    df.drop(columns="_id", inplace=True)

df["timestamp"] = pd.to_datetime(df["timestamp"])

df = df.sort_values("timestamp")

df.reset_index(drop=True, inplace=True)

print(df.shape)

df.head()

(8498, 18)

,timestamp,city,aqi,aqi_change_rate,co,day,day_of_week,hour,humidity,month,no2,o3,pm10,pm25,pressure,so2,temperature,wind_speed
0,2025-08-15 11:00:00+00:00,karachi,60,0.0,80.73,15,4,11,63.0,8,0.05,38.67,54.27,16.60,998.1,0.15,31.5,13.2
1,2025-08-15 12:00:00+00:00,karachi,62,2.0,80.36,15,4,12,72.0,8,0.06,38.42,55.99,17.14,998.5,0.16,30.3,12.7
2,2025-08-15 13:00:00+00:00,karachi,63,1.0,80.13,15,4,13,71.0,8,0.08,38.36,58.14,17.65,999.1,0.16,30.2,9.7
3,2025-08-15 14:00:00+00:00,karachi,63,0.0,79.89,15,4,14,75.0,8,0.10,38.20,60.32,18.02,999.5,0.17,29.5,8.5
4,2025-08-15 15:00:00+00:00,karachi,64,1.0,79.53,15,4,15,79.0,8,0.10,38.08,62.35,18.19,1000.1,0.17,29.0,8.3

In [74]:
import os

print(os.getcwd())

c:\Projects\10 Pearls Internship Project\Air-Quality-Index-Predictor\app\notebooks

In [75]:
import sys

for p in sys.path:
    print(p)

C:\Users\msubh\AppData\Local\Programs\Python\Python311\python311.zip
C:\Users\msubh\AppData\Local\Programs\Python\Python311\DLLs
C:\Users\msubh\AppData\Local\Programs\Python\Python311\Lib
C:\Users\msubh\AppData\Local\Programs\Python\Python311
c:\Projects\10 Pearls Internship Project\Air-Quality-Index-Predictor\venv

c:\Projects\10 Pearls Internship Project\Air-Quality-Index-Predictor\venv\Lib\site-packages
c:\Projects\10 Pearls Internship Project\Air-Quality-Index-Predictor\app
c:\Projects\10 Pearls Internship Project\Air-Quality-Index-Predictor\app
c:\Projects\10 Pearls Internship Project\Air-Quality-Index-Predictor\app
c:\Projects\10 Pearls Internship Project\Air-Quality-Index-Predictor\app

In [76]:
from pathlib import Path

current = Path.cwd()

print("Current:", current)
print("Parent:", current.parent)
print("Parent Parent:", current.parent.parent)

Current: c:\Projects\10 Pearls Internship Project\Air-Quality-Index-Predictor\app\notebooks
Parent: c:\Projects\10 Pearls Internship Project\Air-Quality-Index-Predictor\app
Parent Parent: c:\Projects\10 Pearls Internship Project\Air-Quality-Index-Predictor

In [77]:
from pathlib import Path

for item in Path.cwd().parent.iterdir():
    print(item.name)

.github
main.py
models
notebooks
routes
src
__init__.py
__pycache__

In [78]:
from src.features.feature_engineering import (
    build_training_features
)

df = build_training_features(df)

df.head(30)

,timestamp,city,aqi,aqi_change_rate,co,day,day_of_week,hour,humidity,month,...,aqi_lag_6,aqi_lag_12,aqi_lag_24,pm25_lag_1,pm25_lag_6,pm25_lag_24,aqi_roll_mean_6,aqi_roll_mean_12,aqi_roll_mean_24,aqi_roll_std_24
0,2025-08-15 11:00:00+00:00,karachi,60,0.0,80.73,15,4,11,63.0,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-08-15 12:00:00+00:00,karachi,62,2.0,80.36,15,4,12,72.0,8,...,NaN,NaN,NaN,16.60,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-08-15 13:00:00+00:00,karachi,63,1.0,80.13,15,4,13,71.0,8,...,NaN,NaN,NaN,17.14,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-08-15 14:00:00+00:00,karachi,63,0.0,79.89,15,4,14,75.0,8,...,NaN,NaN,NaN,17.65,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-08-15 15:00:00+00:00,karachi,64,1.0,79.53,15,4,15,79.0,8,...,NaN,NaN,NaN,18.02,NaN,NaN,NaN,NaN,NaN,NaN
5,2025-08-15 16:00:00+00:00,karachi,64,0.0,79.30,15,4,16,80.0,8,...,NaN,NaN,NaN,18.19,NaN,NaN,62.666667,NaN,NaN,NaN
6,2025-08-15 17:00:00+00:00,karachi,63,-1.0,79.17,15,4,17,82.0,8,...,60.0,NaN,NaN,18.10,16.60,NaN,63.166667,NaN,NaN,NaN
7,2025-08-15 18:00:00+00:00,karachi,61,-2.0,79.13,15,4,18,84.0,8,...,62.0,NaN,NaN,17.65,17.14,NaN,63.000000,NaN,NaN,NaN
8,2025-08-15 19:00:00+00:00,karachi,59,-2.0,79.15,15,4,19,85.0,8,...,63.0,NaN,NaN,16.98,17.65,NaN,62.333333,NaN,NaN,NaN
9,2025-08-15 20:00:00+00:00,karachi,58,-1.0,79.18,15,4,20,87.0,8,...,63.0,NaN,NaN,16.12,18.02,NaN,61.500000,NaN,NaN,NaN
10,2025-08-15 21:00:00+00:00,karachi,57,-1.0,79.27,15,4,21,88.0,8,...,64.0,NaN,NaN,15.36,18.19,NaN,60.333333,NaN,NaN,NaN
11,2025-08-15 22:00:00+00:00,karachi,56,-1.0,79.51,15,4,22,89.0,8,...,64.0,NaN,NaN,14.74,18.10,NaN,59.000000,60.833333,NaN,NaN
12,2025-08-15 23:00:00+00:00,karachi,55,-1.0,79.78,15,4,23,91.0,8,...,63.0,60.0,NaN,14.24,17.65,NaN,57.666667,60.416667,NaN,NaN
13,2025-08-16 00:00:00+00:00,karachi,54,-1.0,80.03,16,5,0,92.0,8,...,61.0,62.0,NaN,13.92,16.98,NaN,56.500000,59.750000,NaN,NaN
14,2025-08-16 01:00:00+00:00,karachi,54,0.0,80.09,16,5,1,92.0,8,...,59.0,63.0,NaN,13.74,16.12,NaN,55.666667,59.000000,NaN,NaN
15,2025-08-16 02:00:00+00:00,karachi,54,0.0,80.34,16,5,2,91.0,8,...,58.0,63.0,NaN,13.65,15.36,NaN,55.000000,58.250000,NaN,NaN
16,2025-08-16 03:00:00+00:00,karachi,54,0.0,80.50,16,5,3,83.0,8,...,57.0,64.0,NaN,13.59,14.74,NaN,54.500000,57.416667,NaN,NaN
17,2025-08-16 04:00:00+00:00,karachi,54,0.0,80.69,16,5,4,77.0,8,...,56.0,64.0,NaN,13.58,14.24,NaN,54.166667,56.583333,NaN,NaN
18,2025-08-16 05:00:00+00:00,karachi,54,0.0,80.81,16,5,5,72.0,8,...,55.0,63.0,NaN,13.57,13.92,NaN,54.000000,55.833333,NaN,NaN
19,2025-08-16 06:00:00+00:00,karachi,54,0.0,80.95,16,5,6,65.0,8,...,54.0,61.0,NaN,13.56,13.74,NaN,54.000000,55.250000,NaN,NaN
20,2025-08-16 07:00:00+00:00,karachi,54,0.0,81.00,16,5,7,61.0,8,...,54.0,59.0,NaN,13.57,13.65,NaN,54.000000,54.833333,NaN,NaN
21,2025-08-16 08:00:00+00:00,karachi,54,0.0,81.04,16,5,8,63.0,8,...,54.0,58.0,NaN,13.53,13.59,NaN,54.000000,54.500000,NaN,NaN
22,2025-08-16 09:00:00+00:00,karachi,54,0.0,81.05,16,5,9,62.0,8,...,54.0,57.0,NaN,13.49,13.58,NaN,54.000000,54.250000,NaN,NaN
23,2025-08-16 10:00:00+00:00,karachi,54,0.0,81.38,16,5,10,61.0,8,...,54.0,56.0,NaN,13.43,13.57,NaN,54.000000,54.083333,57.458333,3.956054
24,2025-08-16 11:00:00+00:00,karachi,54,0.0,81.72,16,5,11,64.0,8,...,54.0,55.0,60.0,13.45,13.56,16.60,54.000000,54.000000,57.208333,3.977974
25,2025-08-16 12:00:00+00:00,karachi,54,0.0,82.14,16,5,12,71.0,8,...,54.0,54.0,62.0,13.54,13.57,17.14,54.000000,54.000000,56.875000,3.893277
26,2025-08-16 13:00:00+00:00,karachi,55,1.0,83.01,16,5,13,71.0,8,...,54.0,54.0,63.0,13.66,13.53,17.65,54.166667,54.083333,56.541667,3.682853
27,2025-08-16 14:00:00+00:00,karachi,55,0.0,84.02,16,5,14,78.0,8,...,54.0,54.0,63.0,13.86,13.49,18.02,54.333333,54.166667,56.208333,3.425977
28,2025-08-16 15:00:00+00:00,karachi,55,0.0,84.96,16,5,15,80.0,8,...,54.0,54.0,64.0,14.03,13.43,18.19,54.500000,54.250000,55.833333,3.002414
29,2025-08-16 16:00:00+00:00,karachi,56,1.0,85.81,16,5,16,81.0,8,...,54.0,54.0,64.0,14.21,13.45,18.10,54.833333,54.416667,55.500000,2.449490

In [79]:
# # AQI rolling mean
# df["aqi_roll_mean_6"] = df["aqi"].rolling(6).mean()

# df["aqi_roll_mean_12"] = df["aqi"].rolling(12).mean()

# df["aqi_roll_mean_24"] = df["aqi"].rolling(24).mean()

# # AQI rolling standard deviation
# df["aqi_roll_std_24"] = df["aqi"].rolling(24).std()

# df.head(30)

In [80]:
# Day 1 (next 24 hours)
df["target_day1"] = [
    df["aqi"].iloc[i+1:i+25].mean()
    if i + 24 < len(df)
    else np.nan
    for i in range(len(df))
]

# Day 2 (25–48 hours)
df["target_day2"] = [
    df["aqi"].iloc[i+25:i+49].mean()
    if i + 48 < len(df)
    else np.nan
    for i in range(len(df))
]

# Day 3 (49–72 hours)
df["target_day3"] = [
    df["aqi"].iloc[i+49:i+73].mean()
    if i + 72 < len(df)
    else np.nan
    for i in range(len(df))
]

In [81]:
df = df.dropna()

df.reset_index(drop=True, inplace=True)

print(df.shape)

(8402, 33)

In [82]:
FEATURES = [

    # Calendar
    "hour",
    "day",
    "month",
    "day_of_week",

    # Pollutants
    "pm25",
    "pm10",
    "o3",
    "no2",
    "so2",
    "co",

    # Weather
    "temperature",
    "humidity",
    "pressure",
    "wind_speed",

    # AQI lag
    "aqi_lag_1",
    "aqi_lag_3",
    "aqi_lag_6",
    "aqi_lag_12",
    "aqi_lag_24",

    # PM2.5 lag
    "pm25_lag_1",
    "pm25_lag_6",
    "pm25_lag_24",

    # Rolling
    "aqi_roll_mean_6",
    "aqi_roll_mean_12",
    "aqi_roll_mean_24",
    "aqi_roll_std_24",
]

In [83]:
X = df[FEATURES]

y_day1 = df["target_day1"]

y_day2 = df["target_day2"]

y_day3 = df["target_day3"]

print(X.shape)

(8402, 26)

In [84]:
from sklearn.model_selection import train_test_split

X_train, X_test, y1_train, y1_test = train_test_split(
    X,
    y_day1,
    test_size=0.2,
    shuffle=False,
)

_, _, y2_train, y2_test = train_test_split(
    X,
    y_day2,
    test_size=0.2,
    shuffle=False,
)

_, _, y3_train, y3_test = train_test_split(
    X,
    y_day3,
    test_size=0.2,
    shuffle=False,
)

In [85]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
)

import numpy as np
import pandas as pd

In [86]:
from xgboost import XGBRegressor

In [87]:
xgb_day1 = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1,
)

xgb_day1.fit(X_train, y1_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=-1, num_parallel_tree=None, ...)

In [88]:
xgb_day2 = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1,
)

xgb_day2.fit(X_train, y2_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=-1, num_parallel_tree=None, ...)

In [89]:
xgb_day3 = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1,
)

xgb_day3.fit(X_train, y3_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=-1, num_parallel_tree=None, ...)

In [90]:
pred_day1 = xgb_day1.predict(X_test)

pred_day2 = xgb_day2.predict(X_test)

pred_day3 = xgb_day3.predict(X_test)

In [91]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [92]:
day1_mae = mean_absolute_error(y1_test, pred_day1)
day1_rmse = np.sqrt(mean_squared_error(y1_test, pred_day1))
day1_r2 = r2_score(y1_test, pred_day1)

day2_mae = mean_absolute_error(y2_test, pred_day2)
day2_rmse = np.sqrt(mean_squared_error(y2_test, pred_day2))
day2_r2 = r2_score(y2_test, pred_day2)

day3_mae = mean_absolute_error(y3_test, pred_day3)
day3_rmse = np.sqrt(mean_squared_error(y3_test, pred_day3))
day3_r2 = r2_score(y3_test, pred_day3)

print(f"Day 1 - MAE: {day1_mae:.2f}, RMSE: {day1_rmse:.2f}, R2: {day1_r2:.2f}")
print(f"Day 2 - MAE: {day2_mae:.2f}, RMSE: {day2_rmse:.2f}, R2: {day2_r2:.2f}")
print(f"Day 3 - MAE: {day3_mae:.2f}, RMSE: {day3_rmse:.2f}, R2: {day3_r2:.2f}")

Day 1 - MAE: 5.72, RMSE: 9.02, R2: 0.71
Day 2 - MAE: 10.58, RMSE: 14.99, R2: 0.20
Day 3 - MAE: 12.55, RMSE: 16.87, R2: -0.02

In [93]:
import joblib

joblib.dump(xgb_day1, "../models/xgboost_day1.pkl")

joblib.dump(xgb_day2, "../models/xgboost_day2.pkl")

joblib.dump(xgb_day3, "../models/xgboost_day3.pkl")

print("XGBoost model saved successfully.")

XGBoost model saved successfully.

In [94]:
results = pd.DataFrame({
    "Forecast": [
        "Day 1",
        "Day 2",
        "Day 3",
    ],
    "MAE": [
        day1_mae,
        day2_mae,
        day3_mae,
    ],
    "RMSE": [
        day1_rmse,
        day2_rmse,
        day3_rmse,
    ],
    "R²": [
        day1_r2,
        day2_r2,
        day3_r2,
    ],
})

results

  Forecast        MAE       RMSE        R²
0    Day 1   5.720014   9.022516  0.710571
1    Day 2  10.578830  14.994153  0.202937
2    Day 3  12.547460  16.866597 -0.015239

In [95]:
joblib.dump(FEATURES, "../models/feature_columns.pkl")

['../models/feature_columns.pkl']